#!/bin/bash

pip install .
jupyter nbextension     enable --py --sys-prefix appmode
jupyter serverextension enable --py --sys-prefix appmode

wget https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv

#EOF
